# 1. Database ?? (OCI MySQL 8.x ?? DB)

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# .env ???? ?? ???? ?????.
spring.datasource.url=${OCI_DB_URL}
spring.datasource.username=${OCI_DB_USERNAME}
spring.datasource.password=${OCI_DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10


# 2. JPA / Hibernate ??

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# 3. Redis ??

spring.data.redis.host=${OCI_REDIS_HOST}
spring.data.redis.port=${OCI_REDIS_PORT}


# 4. ????

logging.level.org.hibernate.type.descriptor.sql=trace